### ISSUE TITLE
PR 템플릿

### ISSUE THREAD

**Issue by ka-MS** [ka-MS/GodOfJava#4]
# Pull Request Template

### 개발 내용 작성
- [ ] #5
  - 추가된 기능의 목적, 사용 방법 등에 대해 자세하게 기술합니다.
- [ ] 기능 추가 2에 대한 설명
  - 구현된 기능이 어떤 문제를 해결하는지 기술합니다.

## 3. Todo (선택)

- [ ] Todo 1
- [ ] Todo 2
- [ ] Todo 3

- [ ] 이 PR은 반드시 필요한 변경을 포함하고 있습니까?
- [ ] 모든 체크리스트 항목을 검토했습니까?
